/**
 * @file ite_module.h
 * @brief  包含常用头文件
 * @author  <itarge@itarge.com>
 * @version 1.0.0
 * @date 2017-03-10
 */

/* Copyright (C) 2009-2016, Itarge Inc.
 * All right reserved
 *
 */

#ifndef __ITE_MODULE_H__
#define __ITE_MODULE_H__


#ifdef __cplusplus
extern "C" {
#endif

/* 模块号定义， 便于通过错误返回值快速定位模块 */
typedef enum E_ITE_MODULE
{
    E_ITE_MODULE_LOG = 0,       /* 日志模块 */
    E_ITE_MODULE_RTC,           /* RTC模块 */
    E_ITE_MODULE_I2C,           /* I2C模块 */
    E_ITE_MODULE_SPI,           /* SPI模块 */
    E_ITE_MODULE_UART,          /* UART模块 */
    E_ITE_MODULE_FPGA,          /* FPGA模块 */
    E_ITE_MODULE_EEPROM,        /* EEPROM模块 */
    E_ITE_MODULE_VIN,           /* Video输入/采集模块 */
    E_ITE_MODULE_GPIO,          /* GPIO 模块 */
    E_ITE_MODULE_TEMPERATURE,   /* 温度传感器模块 */
    E_ITE_MODULE_LOCAL_BUS,     /* 本地总线模块 */
    E_ITE_MODULE_JPEG_SW,       /* jpeg编解码模块 */
    E_ITE_MODULE_MESSAGE,       /* 基于共享内存的消息队列模块 */
    E_ITE_MODULE_SHM,           /* 共享内存模块 */
    E_ITE_MODULE_MSG,           /* 消息队列模块 */
    E_ITE_MODULE_SEM,           /* Posix信号量模块 */
    E_ITE_MODULE_LOCK,          /* 线程锁模块 */
    E_ITE_MODULE_TASK,          /* 任务模块 */
    E_ITE_MODULE_SWOSD,         /* 软件OSD */
    E_ITE_MODULE_ISP,           /* 图像处理模块 */
    E_ITE_MODULE_ENCODE,        /* 解码模块 */
    E_ITE_MODULE_WATCHDOG,      /* 看门狗模块 */
    E_ITE_MODULE_SEMAPHORE,     /* System V信号量模块 */
    E_ITE_MODULE_SHARE_BUFFER,  /* 共享buffer模块 */
    E_ITE_MODULE_SECRET,        /* 加密模块 */
    E_ITE_MODULE_PID,           /* 线程模块 */
    E_ITE_MODULE_SYSINFO,       /* 系统信息模块 */
    E_ITE_MODULE_UPGRADE,       /* 升级模块 */
    E_ITE_MODULE_UPGRADE_SERVER,       /* 升级模块 服务器*/
    E_ITE_MODULE_MTD,           /* MTD模块 */
    E_ITE_MODULE_IPC,           /* 核间通讯模块 */
    E_ITE_MODULE_NET,           /* NET模块 */
    E_ITE_MODULE_SOCKET,        /* SOCKET模块 */
    E_ITE_MODULE_HASHCMD,       /* HASHCMD模块 */
    E_ITE_MODULE_MEMCPY,        /* MEMCPY模块 */
    E_ITE_MODULE_PINCTRL,       /* PINCTRL模块 */
    E_ITE_MODULE_XC7060,        /* XC7060 ISP模块(上海) */
    E_ITE_MODULE_CONVERT,       /* 图像转换模块 */
    E_ITE_MODULE_SYSCTRL,       /* 系统控制模块 */
    E_ITE_MODULE_HWINFO,        /* HAL 层信息模块 */
    E_ITE_MODULE_RESIZE,        /* 图片缩放模块 */
    E_ITE_MODULE_VERSION,       /* 版本信息获取模块 */
    E_ITE_MODULE_BOARD_TEST,    /* 硬件测试模块 */
    E_ITE_MODULE_FILE,          /* 文件操作模块 */
    E_ITE_MODULE_LED,           /* LED模块 */
    E_ITE_MODULE_COMPRESS,      /* 压缩解压缩模块 */
    E_ITE_MODULE_PWM,           /* PWM模块 */
    E_ITE_MODULE_IRIS,          /* 自动光圈模块 */
    E_ITE_MODULE_SIL1227,       /* sil1127模块 */
    E_ITE_MODULE_MACHXO2,       /* Machxo2 cpld 模块 */
    E_ITE_MODULE_CRYPTO,        /* 加密相关模块 */
    E_ITE_MODULE_DIR,           /* 目录相关操作模块 */
    E_ITE_MODULE_AUTO_TEST,     /* 自动测试模块 */
} E_ITE_MODULE;

/* bit[31:16] 用于存储模块号，bit[15:0]用于存储错误码 */
#define ITE_MODULE_SHIFT        (16)
/*  转换到高位，便于代码直接使用 */
#define ITE_MODULE_VALUE(m)     (m <<ITE_MODULE_SHIFT)
#define ITE_MODULE_MASK         (0xFFFF0000)
/* bit[15:0] 用于存储错误码 */
#define ITE_ERROR_MASK          (0x0000FFFF)

/* 定义模块号宏，便于使用 */
#define ITE_MODULE_LOG          ITE_MODULE_VALUE(E_ITE_MODULE_LOG)
#define ITE_MODULE_RTC          ITE_MODULE_VALUE(E_ITE_MODULE_RTC)
#define ITE_MODULE_I2C          ITE_MODULE_VALUE(E_ITE_MODULE_I2C)
#define ITE_MODULE_SPI          ITE_MODULE_VALUE(E_ITE_MODULE_SPI)
#define ITE_MODULE_UART         ITE_MODULE_VALUE(E_ITE_MODULE_UART)
#define ITE_MODULE_FPGA         ITE_MODULE_VALUE(E_ITE_MODULE_FPGA)
#define ITE_MODULE_EEPROM       ITE_MODULE_VALUE(E_ITE_MODULE_EEPROM)
#define ITE_MODULE_VIN          ITE_MODULE_VALUE(E_ITE_MODULE_VIN)
#define ITE_MODULE_GPIO         ITE_MODULE_VALUE(E_ITE_MODULE_GPIO)
#define ITE_MODULE_TEMPERATURE  ITE_MODULE_VALUE(E_ITE_MODULE_TEMPERATURE)
#define ITE_MODULE_LOCAL_BUS    ITE_MODULE_VALUE(E_ITE_MODULE_LOCAL_BUS)
#define ITE_MODULE_JPEG_SW      ITE_MODULE_VALUE(E_ITE_MODULE_JPEG_SW)
#define ITE_MODULE_MESSAGE      ITE_MODULE_VALUE(E_ITE_MODULE_MESSAGE)
#define ITE_MODULE_SHM          ITE_MODULE_VALUE(E_ITE_MODULE_SHM)
#define ITE_MODULE_MSG          ITE_MODULE_VALUE(E_ITE_MODULE_MSG)
#define ITE_MODULE_SEM          ITE_MODULE_VALUE(E_ITE_MODULE_SEM)
#define ITE_MODULE_LOCK         ITE_MODULE_VALUE(E_ITE_MODULE_LOCK)
#define ITE_MODULE_TASK         ITE_MODULE_VALUE(E_ITE_MODULE_TASK)
#define ITE_MODULE_SWOSD        ITE_MODULE_VALUE(E_ITE_MODULE_SWOSD)
#define ITE_MODULE_ISP          ITE_MODULE_VALUE(E_ITE_MODULE_ISP)
#define ITE_MODULE_ENCODE       ITE_MODULE_VALUE(E_ITE_MODULE_ENCODE)
#define ITE_MODULE_WATCHDOG     ITE_MODULE_VALUE(E_ITE_MODULE_WATCHDOG)
#define ITE_MODULE_SEMAPHORE    ITE_MODULE_VALUE(E_ITE_MODULE_SEMAPHORE)
#define ITE_MODULE_SHARE_BUFFER ITE_MODULE_VALUE(E_ITE_MODULE_SHARE_BUFFER)
#define ITE_MODULE_SECRET       ITE_MODULE_VALUE(E_ITE_MODULE_SECRET)
#define ITE_MODULE_PID          ITE_MODULE_VALUE(E_ITE_MODULE_PID)
#define ITE_MODULE_SYSINFO      ITE_MODULE_VALUE(E_ITE_MODULE_SYSINFO)
#define ITE_MODULE_UPGRADE      ITE_MODULE_VALUE(E_ITE_MODULE_UPGRADE)
#define ITE_MODULE_UPGRADE_SERVER      ITE_MODULE_VALUE(E_ITE_MODULE_UPGRADE_SERVER)
#define ITE_MODULE_MTD          ITE_MODULE_VALUE(E_ITE_MODULE_MTD)
#define ITE_MODULE_IPC          ITE_MODULE_VALUE(E_ITE_MODULE_IPC)
#define ITE_MODULE_NET          ITE_MODULE_VALUE(E_ITE_MODULE_NET)
#define ITE_MODULE_SOCKET       ITE_MODULE_VALUE(E_ITE_MODULE_SOCKET)
#define ITE_MODULE_HASHCMD      ITE_MODULE_VALUE(E_ITE_MODULE_HASHCMD)
#define ITE_MODULE_MEMCPY       ITE_MODULE_VALUE(E_ITE_MODULE_MEMCPY)
#define ITE_MODULE_PINCTRL      ITE_MODULE_VALUE(E_ITE_MODULE_PINCTRL)
#define ITE_MODULE_XC7060       ITE_MODULE_VALUE(E_ITE_MODULE_XC7060)
#define ITE_MODULE_CONVERT      ITE_MODULE_VALUE(E_ITE_MODULE_CONVERT)
#define ITE_MODULE_SYSCTRL      ITE_MODULE_VALUE(E_ITE_MODULE_SYSCTRL)
#define ITE_MODULE_HWINFO       ITE_MODULE_VALUE(E_ITE_MODULE_HWINFO)
#define ITE_MODULE_RESIZE       ITE_MODULE_VALUE(E_ITE_MODULE_RESIZE)
#define ITE_MODULE_VERSION      ITE_MODULE_VALUE(E_ITE_MODULE_VERSION)
#define ITE_MODULE_BOARD_TEST   ITE_MODULE_VALUE(E_ITE_MODULE_BOARD_TEST)
#define ITE_MODULE_FILE         ITE_MODULE_VALUE(E_ITE_MODULE_FILE)
#define ITE_MODULE_LED          ITE_MODULE_VALUE(E_ITE_MODULE_LED)
#define ITE_MODULE_COMPRESS     ITE_MODULE_VALUE(E_ITE_MODULE_COMPRESS)
#define ITE_MODULE_PWM          ITE_MODULE_VALUE(E_ITE_MODULE_PWM)
#define ITE_MODULE_IRIS         ITE_MODULE_VALUE(E_ITE_MODULE_IRIS)
#define ITE_MODULE_SIL1127      ITE_MODULE_VALUE(E_ITE_MODULE_SIL1227)
#define ITE_MODULE_MACHXO2      ITE_MODULE_VALUE(E_ITE_MODULE_MACHXO2)
#define ITE_MODULE_CRYPTO       ITE_MODULE_VALUE(E_ITE_MODULE_CRYPTO)
#define ITE_MODULE_DIR          ITE_MODULE_VALUE(E_ITE_MODULE_DIR)
#define ITE_MODULE_AUTO_TEST    ITE_MODULE_VALUE(E_ITE_MODULE_AUTO_TEST)

#ifdef __cplusplus
}
#endif

#endif //__ITE_MODULE_H__
