# (c) Itarge.Inc

include Rules.make

all: help 
clean:
	@echo "clean nothing"

help:
	@echo  "uboot:          uboot"
	@echo  "lsp:            lsp"
	@echo  "uboot_clean:    clean uboot"
	@echo  "lsp_clean:      clean lsp"

libs:
	@echo  "There is no need to compile the library for HOST"

package:
	@echo  "There is no need to compile the package for HOST"

libs_clean:
	@echo  "There is no need to clean the library for HOST"
